src/Entity/Ads.php
<?php

namespace App\Entity;

use App\Entity\Users;
use App\Entity\Images;
use App\Entity\Categories;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AdsRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: AdsRepository::class)]
class Ads
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 45)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'date')]
    private $created_at;

    #[ORM\Column(type: 'date', nullable: true)]
    private $updated_at;

    #[ORM\Column(type: 'date', nullable: true)]
    private $deleted_at;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $url_video;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $url_image;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $isVisible;

    #[ORM\ManyToOne(targetEntity: Users::class, inversedBy: 'ads',cascade:["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    #[ORM\ManyToOne(targetEntity: Categories::class, inversedBy: 'ads')]
    #[ORM\JoinColumn(nullable: false)]
    private $category_id;

    #[ORM\OneToMany(mappedBy: 'adsId', targetEntity: Images::class, orphanRemoval: true,cascade: ["persist"])]
    private $images;

    #[ORM\Column(type: 'integer')]
    private $price;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->created_at = new \DateTime();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = new \DateTime("now");

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeInterface $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function getUrlVideo(): ?string
    {
        return $this->url_video;
    }

    public function setUrlVideo(?string $url_video): self
    {
        $this->url_video = $url_video;

        return $this;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(?string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->isVisible;
    }

    public function setIsVisible(?bool $isVisible): self
    {
        $this->isVisible = $isVisible;

        return $this;
    }

    public function getUserId(): ?Users
    {
        return $this->user_id;
    }

    public function setUserId(?Users $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCategoryId(): ?Categories
    {
        return $this->category_id;
    }

    public function setCategoryId(?Categories $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAdsId($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAdsId() === $this) {
                $image->setAdsId(null);
            }
        }

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Form/AdsType.php
<?php

namespace App\Form;

use App\Entity\Ads;
use App\Entity\Categories;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class AdsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title',TextType::class, [
                'label'=> 'Choisir le titre de votre annonce',
                "attr" => [
                    "class" => "form-control p-2 d-flex justify-content",
                ]
            ])
            ->add('content',TextareaType::class, [
                'label'=> 'Donnez une description a votre annonce',
                "attr" => [
                    "class" => "form-control p-2 d-flex justify-content",
                ]
            ])
            ->add('category_id', EntityType::class, [
                'label'=> 'Sélectionner la categorie dans laquelle vous voulez publier votre annonce',
                'class'=> Categories::class,
                'choice_label' => function($categories) {
                    return $categories-> getName();
                },
                'attr' => [
                    "class" => "form d-flex  p-2 justify-content-evenly",
                ]
            ])
            ->add('images', FileType::class, [
                'label' => 'Sélectionner les images sur votre ordinateur',
                'multiple' => true,
                'mapped' => false,
                'required' => false,
                "attr" => [
                    "class" => "form-control  p-2 d-flex justify-content",
                    "for"=> "formFileMultiple"
                ],
                //  'constraints' => [
                //      new Image([
                //          'maxSize' => '5M',
                //          'mimeTypes' => [
                //              'image/*',
                             
                //          ]
                //      ])
                //  ]
                // https://symfonycasts.com/screencast/symfony-uploads/validation 
         ])
          
            // ->add('url_video',TextType::class, [
            //     'required' => false,
            //     "attr" => [
            //         "class" => "form d-flex justify-content",
            //     ]
            // ])
           
            ->add('price',TextType::class, [
                "attr" => [
                    "class" => "form-control  p-2 d-flex justify-content",
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ads::class,
        ]);
    }
}

src/Controller/AdsController.php
<?php

namespace App\Controller;

use App\Entity\Ads;
use App\Entity\Users;
use App\Form\AdsType;
use App\Entity\Images;
use App\Entity\Categories;
use App\Repository\AdsRepository;
use Symfony\Component\Mime\Email;
use App\Repository\ImagesRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/ads')]
class AdsController extends AbstractController
{
    #[Route('/', name: 'app_ads_index', methods: ['GET'])]
    public function index(AdsRepository $adsRepository): Response
    {
        $user = $this->getUser();

        $ads = $adsRepository->findBy(['user_id' => $user]);

        return $this->render('ads/index.html.twig', [
            'ads' => $ads
        ]);
    }

    #[Route('/new', name: 'app_ads_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AdsRepository $adsRepository,MailerInterface $mailer, ManagerRegistry $doctrine): Response
    {
        $ad = new Ads();

        $allCat = $doctrine->getRepository(Categories::class)->findAll();
        $usermodo = $doctrine->getRepository(Users::class)->findAll();

        $form = $this->createForm(AdsType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // on recupere les images transmises
            $images = $form->get('images')->getData();
            // on boucle sur les images
            foreach ($images as $image) {
                // on genere un nouveau fichier 
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();
                // on copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier

                );
                // on stocke l'image dans la base de donnees son nom
                $img = new Images();

                $img->setImageName($fichier);

                $ad->addImage($img);
            }
            $user = $this->getUser();
            $ad->setUserId($user);
            $cat = $doctrine->getRepository(Categories::class)->find($ad->getCategoryId());
            $ad->setCategoryId($cat);
            $ad->setIsVisible(true);

            $adsRepository->add($ad);
        
            foreach( $usermodo as $el)
            {
                $roles = $el->getRoles();
                $username = $user->getUserIdentifier();

               if(in_array("ROLE_MODO", $roles))
               {
                   $email = (new Email())
                    ->from('admin@example.com')
                    ->to($el->getEmail())
                    ->subject('nouvelle annonce')
                    ->text("Une nouvelle annonce vient d'etre publié par{ $username }");
                    $mailer->send($email);
               }

            }
            return $this->redirectToRoute('app_ads_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ads/new.html.twig', [
            'ad' => $ad,
            'form' => $form,
            'categories' => $allCat,

        ]);
    }

    #[Route('/{id}', name: 'app_ads_show', methods: ['GET'])]
    public function show(Ads $ad): Response
    {
        return $this->render('ads/show.html.twig', [
            'ad' => $ad,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ads_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ads $ad, AdsRepository $adsRepository, ManagerRegistry $doctrine): Response
    {
        $form = $this->createForm(AdsType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
          
            $images = $form->get('images')->getData();
            // on boucle sur les images
            foreach ($images as $image) {
                // on genere un nouveau fichier 
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();
                // on copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier

                );
                // on stocke l'image dans la base de donnees son nom
                
                $img = new Images();
                $img->setImageName($fichier);
                $ad->addImage($img);
            }
            $user = $this->getUser();
            $ad->setUserId($user);
            $cat = $doctrine->getRepository(Categories::class)->find($ad->getCategoryId());
            $ad->setCategoryId($cat);
            $ad->setIsVisible(true);

            $adsRepository->add($ad);
           
            
            return $this->redirectToRoute('app_ads_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ads/edit.html.twig', [
            'ad' => $ad,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ads_delete', methods: ['POST'])]
    public function delete(Request $request, Ads $ad, AdsRepository $adsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $ad->getId(), $request->request->get('_token'))) {
            $adsRepository->remove($ad);
        }

        return $this->redirectToRoute('app_ads_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/delete/image/{id}', name: 'app_image_delete', methods: ['DELETE'])]
    public function deleteImage(Images $image, Request $request, ImagesRepository $ImagesRepository)
    {
        $data = json_decode($request->getContent(), true);
        // on verifie si token est valide
        if ($this->isCsrfTokenValid('delete' . $image->getId(), $data['_token'])) {
            $nom = $image->getImageName();
            $ImagesRepository->remove($image);
            unlink($this->getParameter('images_directory') . '/' . $nom);

            //return $this->redirectToRoute('app_ads_index', [], Response::HTTP_SEE_OTHER);
            return new JsonResponse(['success' => 1]);
        } else {
            return new JsonResponse(['error' => 'Token Invalide'], 400);
        }
    }
    #[Route('/view/{id}', name: 'app_ads_view')]
    public function adsShow(ManagerRegistry $doctrine, $id)
    {
        $ads = $doctrine->getRepository(Ads::class)->findOneBy(['id' => $id]);
        return $this->render('ads/show_ads.html.twig', [
            'ads' => $ads,
        ]);
    }
}

templates/ads/_delete_form.html.twig
<form method="post" action="{{ path('app_ads_delete', {'id': ad.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ad.id) }}">
    <button class="btn btn-primary">Supprimer</button>
</form>

templates/ads/_form.html.twig
<div class="bg-secondary p-2" style="--bs-bg-opacity: .5;">
	<div class="form-control bg-secondary p-2" style="--bs-bg-opacity: .5;">
		{{ form_start(form) }}

		{{ form_widget(form) }}


		{% if app.request.attributes.get('_route')=='app_ads_edit' %}

			<h4>Images pour l'annonce</h4>
			{% for image in ad.images %}
				<figure class="figure d-flex justify-content">
					<img src="/uploads/{{ image.imageName }}" class="d-flex justify-content figure-img img-fluid rounded" alt="Image" width="200">
					<figcaption class="figure-caption">Sélectionner photos sur pc</figcaption>
					<a class="" href="/ads/delete/image/{{ image.id }}" data-delete data-token="{{ csrf_token('delete' ~ image.id)}}">Supprimer Image</a>
				</figure>
			{% endfor %}
		{% endif %}

		<button type="submit" class="btn btn-primary">{{ button_label|default('Publier mon annonce') }}</button>

		{{ form_end(form) }}
	</div>
</div>

templates/ads/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
	<div class=" container bg-secondary p-2" style="--bs-bg-opacity: .5;">

		<h1 class="text-center">Modifier votre annonce</h1>

		{{ include('ads/_form.html.twig', {'button_label': 'Update'}) }}

		{% block javascripts %}
			<script src="{{ asset('js/images.js') }}"></script>
		{% endblock %}


		<a class="nav-link link-dark" href="{{ path('app_ads_index') }}">Cliquer pour revenir à la page précédente</a>

		{{ include('ads/_delete_form.html.twig') }}
	</div>
{% endblock %}

templates/ads/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ads index
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="text-center">Annonces</h1>

		<table class="table  bg-secondary p-2" style="--bs-bg-opacity: .5;">
			<thead>
				<tr>
					<th>Titre</th>
					<th>Description</th>
					<th>Image</th>
					<th>Créer le</th>
					<th>Url_video</th>
					<th>Visibilité</th>
					<th>Catégorie</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>

				{% for ad in ads %}
					<tr>
						<td>{{ ad.title }}</td>
						<td>{{ ad.content|length > 50 ? ad.content|slice(0,50) ~ '...' : ad.content }}</td>
						<td>
							{% for image in ad.images|slice(0,1) %}
								<img src="/uploads/{{ image.imageName }}" alt="Image" width="50">
							{% endfor %}
						</td>
						<td>{{ ad.createdAt ? ad.createdAt|date('Y-m-d') : '' }}</td>
						<td>{{ ad.urlVideo }}</td>
						<td>{{ ad.isVisible ? 'Yes' : 'No' }}</td>
						<td>{{ ad.categoryId }}</td>
						<td>
							<a class="nav-link link-dark" type="button" type="button" href="{{ path('app_ads_show', {'id': ad.id}) }}">Voir</a>

							<a class="nav-link link-dark" type="button" type="button" href="{{ path('app_ads_edit', {'id': ad.id}) }}">Éditer</a>

						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="10">Pas d'annonce trouvé</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		<a href="{{ path('app_ads_new') }}">Créer une annonce</a>
	</div>
{% endblock %}

templates/ads/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ads
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Create new Ads</h1>

		{{ include('ads/_form.html.twig') }}

		<a class="nav-link link-dark text-center" type="button" href="{{ path('app_ads_index') }}">Cliquer pour revenir à la page précédente</a>
	</div>


{% endblock %}

templates/ads/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ads{% endblock %}

{% block body %}
    <h1>Ads</h1>

    <table class="table bg-secondary p-2" style="--bs-bg-opacity: .5;">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ad.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ ad.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ ad.content }}</td>
            </tr>
            <tr>
            {% for image in ad.images %}
            <th>Image</th>
			<td><img src="/uploads/{{ image.imageName }}" alt="Image" width="200"></td>
			
		   {% endfor %}
           </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ ad.createdAt ? ad.createdAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ ad.updatedAt ? ad.updatedAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ ad.deletedAt ? ad.deletedAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Url_video</th>
                <td>{{ ad.urlVideo }}</td>
            </tr>
            <tr>
                <th>IsVisible</th>
                <td>{{ ad.isVisible ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_ads_index') }}">back to list</a>

    <a href="{{ path('app_ads_edit', {'id': ad.id}) }}">edit</a>

    {{ include('ads/_delete_form.html.twig') }}
{% endblock %}

templates/ads/show_ads.html.twig
{% extends 'base.html.twig' %}



{% block body %}


<div class="container bg-secondary p-2" style="--bs-bg-opacity: .5;">
    <h1 class="text-center">{{ ads.title }}</h1>
    <p class="text-center">{{ ads.content }}</p>

    {% for adImage in ads.images %}
    <div class="text-center">
    <img  src="/uploads/{{ adImage.imageName }}" style="width:30%;">
    </div>
    {% endfor %}
    <a href="/send">Envoyer un message</a>
</div>


{% endblock %}